/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721 from "./ERC721";
export type { erc721 };
import type * as onstargramSol from "./Onstargram.sol";
export type { onstargramSol };
export * as factories from "./factories";
export type { ERC165 } from "./ERC721/ERC165";
export { ERC165__factory } from "./factories/ERC721/ERC165__factory";
export type { ERC721 } from "./ERC721/ERC721";
export { ERC721__factory } from "./factories/ERC721/ERC721__factory";
export type { ERC721Enumerable } from "./ERC721/ERC721Enumerable";
export { ERC721Enumerable__factory } from "./factories/ERC721/ERC721Enumerable__factory";
export type { IERC165 } from "./ERC721/IERC165";
export { IERC165__factory } from "./factories/ERC721/IERC165__factory";
export type { IERC721 } from "./ERC721/IERC721";
export { IERC721__factory } from "./factories/ERC721/IERC721__factory";
export type { IERC721Enumerable } from "./ERC721/IERC721Enumerable";
export { IERC721Enumerable__factory } from "./factories/ERC721/IERC721Enumerable__factory";
export type { IERC721Receiver } from "./ERC721/IERC721Receiver";
export { IERC721Receiver__factory } from "./factories/ERC721/IERC721Receiver__factory";
export type { Onstagram } from "./Onstargram.sol/Onstagram";
export { Onstagram__factory } from "./factories/Onstargram.sol/Onstagram__factory";
